## Домашнє завдання 3.2. Тема 3. Основи роботи з бібліотеками Numpy, Pandas, Matplotlib, Plotly
Виконавець: Черемісін

 У цьому домашньому завданні ми будемо працювати з набором даних Tips. Нижче інформація про нього.

 Про датасет:

 Tips - це датасет, який містить інформацію про рахунки та чайові в ресторані.

 Колонки датасету:

 total_bill - загальна сума рахунку (долари)
 tip - розмір чайових (долари)
 sex - стать відвідувача (Male/Female)
 smoker - чи курить (Yes/No)
 day - день тижня (Thur/Fri/Sat/Sun)
 time - час відвідування (Lunch/Dinner)
 size - розмір групи (кількість людей)
 Джерело: Оригінальні дані зібрані в одному з американських ресторанів у 1990-х роках. Скачати і переглянути набір даних можна тут: https://www.kaggle.com/datasets/sakshisatre/tips-dataset

 А також ми вже вивантажили файл з даними і завантажили вам у Матеріали до цього модуля.

In [2]:
import pandas as pd

### 1. Завантаження та огляд

Завантажте датасет Tips (Чайові) з файла у матеріалах tips.csv.

Виведіть (кожен пункт оцінюється в 0.5 бала):

Перші 5 рядків

Розмір датасету (shape)

Назви всіх колонок

Інформацію про типи даних (info)

In [4]:
df = pd.read_csv('tip.csv')

In [7]:
display(df.head(5))

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
display(df.shape)

(244, 7)

In [11]:
display(df.columns)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [16]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

None

### 2. Базова вибірка даних

Виберіть та виведіть (кожен пункт оцінюється в 0.5 бала):

Колонку total_bill (загальний рахунок)

Колонки total_bill та tip (чайові) разом

Перші 10 рядків

Рядок з індексом 5

In [18]:
total_bill = df['total_bill']
print(total_bill)

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [20]:
two_col = df[['total_bill', 'tip']]
print(two_col)

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [21]:
ten_col = df.loc[0:9]
print(ten_col)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [27]:
five_row = df.loc[5]
print(five_row)

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

### 3. Фільтрація даних

Відфільтруйте повний набір даних та виведіть (кожен пункт оцінюється в 0.5 бала):

Всі рахунки більше 20 доларів (total_bill > 20)

Всі відвідувачі-жінки (sex == 'Female')

Рахунки на вечерю (time == 'Dinner')

Рахунки на вечерю з сумою чеку більше 30 доларів

Для виведення результатів фільтрації:

зберегти результат у окрему змінну

показати кількість записів у відфільтрованому наборі

вивести перші 5 записів відфільтрованого набору.

In [33]:
#Всі рахунки більше 20 доларів (total_bill > 20)

over_20 = df[df['total_bill'] > 20]
print(over_20)

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
237       32.83  1.17    Male    Yes  Sat  Dinner     2
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2

[97 rows x 7 columns]

In [36]:
print(over_20.shape)

(97, 7)

In [37]:
print(over_20.head(5))

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

In [ ]:
#Всі відвідувачі-жінки (sex == 'Female')

In [39]:
fem = df[df['sex'] == 'Female']
print(fem)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
..          ...   ...     ...    ...   ...     ...   ...
226       10.09  2.00  Female    Yes   Fri   Lunch     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[87 rows x 7 columns]

In [40]:
print(fem.shape)

(87, 7)

In [41]:
print(fem.head(5))

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3

In [ ]:
#Рахунки на вечерю (time == 'Dinner')

In [42]:
din = df[df['time'] == 'Dinner']
print(din)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[176 rows x 7 columns]

In [43]:
print(din.shape)

(176, 7)

In [44]:
print(din.head(5))

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
#Рахунки на вечерю з сумою чеку більше 30 доларів
#Варіант 1

In [45]:
din_over_30 = din[din['total_bill'] > 30]
print(din_over_30)

     total_bill    tip     sex smoker  day    time  size
11        35.26   5.00  Female     No  Sun  Dinner     4
23        39.42   7.58    Male     No  Sat  Dinner     4
39        31.27   5.00    Male     No  Sat  Dinner     3
44        30.40   5.60    Male     No  Sun  Dinner     4
47        32.40   6.00    Male     No  Sun  Dinner     4
52        34.81   5.20  Female     No  Sun  Dinner     4
56        38.01   3.00    Male    Yes  Sat  Dinner     4
59        48.27   6.73    Male     No  Sat  Dinner     4
95        40.17   4.73    Male    Yes  Fri  Dinner     4
102       44.30   2.50  Female    Yes  Sat  Dinner     3
112       38.07   4.00    Male     No  Sun  Dinner     3
156       48.17   5.00    Male     No  Sun  Dinner     6
167       31.71   4.50    Male     No  Sun  Dinner     4
170       50.81  10.00    Male    Yes  Sat  Dinner     3
173       31.85   3.18    Male    Yes  Sun  Dinner     2
175       32.90   3.11    Male    Yes  Sun  Dinner     2
179       34.63   3.55    Male    Yes  Sun  Dinner     2
180       34.65   3.68    Male    Yes  Sun  Dinner     4
182       45.35   3.50    Male    Yes  Sun  Dinner     3
184       40.55   3.00    Male    Yes  Sun  Dinner     2
187       30.46   2.00    Male    Yes  Sun  Dinner     5
207       38.73   3.00    Male    Yes  Sat  Dinner     4
210       30.06   2.00    Male    Yes  Sat  Dinner     3
212       48.33   9.00    Male     No  Sat  Dinner     4
219       30.14   3.09  Female    Yes  Sat  Dinner     4
237       32.83   1.17    Male    Yes  Sat  Dinner     2
238       35.83   4.67  Female     No  Sat  Dinner     3

In [46]:
print(din_over_30.shape)

(27, 7)

In [47]:
print(din_over_30.head(5))

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4

In [ ]:
#Рахунки на вечерю з сумою чеку більше 30 доларів
#Варіант 2

In [51]:
din_over_30_2 = df[(df['total_bill'] > 30) & (df['time'] == 'Dinner')]
print(din_over_30_2)

     total_bill    tip     sex smoker  day    time  size
11        35.26   5.00  Female     No  Sun  Dinner     4
23        39.42   7.58    Male     No  Sat  Dinner     4
39        31.27   5.00    Male     No  Sat  Dinner     3
44        30.40   5.60    Male     No  Sun  Dinner     4
47        32.40   6.00    Male     No  Sun  Dinner     4
52        34.81   5.20  Female     No  Sun  Dinner     4
56        38.01   3.00    Male    Yes  Sat  Dinner     4
59        48.27   6.73    Male     No  Sat  Dinner     4
95        40.17   4.73    Male    Yes  Fri  Dinner     4
102       44.30   2.50  Female    Yes  Sat  Dinner     3
112       38.07   4.00    Male     No  Sun  Dinner     3
156       48.17   5.00    Male     No  Sun  Dinner     6
167       31.71   4.50    Male     No  Sun  Dinner     4
170       50.81  10.00    Male    Yes  Sat  Dinner     3
173       31.85   3.18    Male    Yes  Sun  Dinner     2
175       32.90   3.11    Male    Yes  Sun  Dinner     2
179       34.63   3.55    Male    Yes  Sun  Dinner     2
180       34.65   3.68    Male    Yes  Sun  Dinner     4
182       45.35   3.50    Male    Yes  Sun  Dinner     3
184       40.55   3.00    Male    Yes  Sun  Dinner     2
187       30.46   2.00    Male    Yes  Sun  Dinner     5
207       38.73   3.00    Male    Yes  Sat  Dinner     4
210       30.06   2.00    Male    Yes  Sat  Dinner     3
212       48.33   9.00    Male     No  Sat  Dinner     4
219       30.14   3.09  Female    Yes  Sat  Dinner     4
237       32.83   1.17    Male    Yes  Sat  Dinner     2
238       35.83   4.67  Female     No  Sat  Dinner     3

In [52]:
print(din_over_30_2.shape)

(27, 7)

In [53]:
print(din_over_30_2.head(5))

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4

### 4. Описова статистика

Обчисліть (кожен пункт оцінюється в 0.5 бала):

In [ ]:
#Середній розмір рахунку на всьому наборі даних

In [59]:
aver_bill = df['total_bill'].mean()
print(aver_bill)

19.78594262295082

In [ ]:
#Кількість пропущених значень у всіх колонках

In [62]:
lost_count = df.isnull().sum()
print(lost_count)

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
#Скільки в наборі даних рахунків за обіди і за вечері

In [79]:
lanch_dinner_count = df.time.value_counts()
print(lanch_dinner_count)

time
Dinner    176
Lunch      68
Name: count, dtype: int64

### 5. Статистика із групуванням

Обчисліть (кожен пункт оцінюється в 0.5 бала):

In [78]:
#Середній рахунок за статтю (groupby sex)

In [80]:
by_sex = df.groupby('sex')['total_bill'].mean()
print("Середній чек за статтю:")
print(by_sex)

Середній чек за статтю:
sex
Female    18.056897
Male      20.744076
Name: total_bill, dtype: float64

In [ ]:
#Середні чайові за днем тижня (groupby day)

In [81]:
by_day = df.groupby('day')['tip'].mean()
print("Середні чайові за днем тиждня:")
print(by_day)

Середні чайові за днем тиждня:
day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

In [ ]:
#Скільки відвідувачів у кожен день

In [105]:
week_or = ['Thur', 'Fri', 'Sat', 'Sun']
df['day'] = pd.Categorical(df['day'], categories=week_or, ordered=True)

visit_by_day = df.groupby('day', observed=False)['size'].sum()
print("Кількість відвідувачів за днем тиждня:")
print(visit_by_day)

Кількість відвідувачів за днем тиждня:
day
Thur    152
Fri      40
Sat     219
Sun     216
Name: size, dtype: int64

### 6. Створення нової колонки

Створіть нову колонку tip_percentage - відсоток чайових від загальної суми рахунку. Виведіть перші 10 рядків з новою колонкою.

In [103]:
df['tip_percentage'] = ((df['tip'] / df['total_bill']) * 100).round(2).map("{} %".format)
print(df['tip_percentage'].head(10))

0     5.94 %
1    16.05 %
2    16.66 %
3    13.98 %
4    14.68 %
5    18.62 %
6    22.81 %
7    11.61 %
8    13.03 %
9    21.85 %
Name: tip_percentage, dtype: object

### 7. Сортування

Відсортуйте датасет і виведіть результат сортування в кожному випадку окремо (кожен пункт оцінюється в 0.5 бала):

За розміром рахунку (зростання)

За чайовими (спадання)

Додатково виведіть топ-5 найбільших чайових використовуючи метод nlargest.

In [106]:
#За розміром рахунку (зростання)

sort_by_bill = df.sort_values('total_bill')
display(sort_by_bill)

     total_bill    tip     sex smoker   day    time  size tip_percentage
67         3.07   1.00  Female    Yes   Sat  Dinner     1        32.57 %
92         5.75   1.00  Female    Yes   Fri  Dinner     2        17.39 %
111        7.25   1.00  Female     No   Sat  Dinner     1        13.79 %
172        7.25   5.15    Male    Yes   Sun  Dinner     2        71.03 %
149        7.51   2.00    Male     No  Thur   Lunch     2        26.63 %
..          ...    ...     ...    ...   ...     ...   ...            ...
182       45.35   3.50    Male    Yes   Sun  Dinner     3         7.72 %
156       48.17   5.00    Male     No   Sun  Dinner     6        10.38 %
59        48.27   6.73    Male     No   Sat  Dinner     4        13.94 %
212       48.33   9.00    Male     No   Sat  Dinner     4        18.62 %
170       50.81  10.00    Male    Yes   Sat  Dinner     3        19.68 %

[244 rows x 8 columns]

In [115]:
#За чайовими (спадання)

sort_by_tip = df.sort_values('tip', ascending=False)
display(sort_by_tip)

     total_bill    tip     sex smoker   day    time  size tip_percentage
170       50.81  10.00    Male    Yes   Sat  Dinner     3        19.68 %
212       48.33   9.00    Male     No   Sat  Dinner     4        18.62 %
23        39.42   7.58    Male     No   Sat  Dinner     4        19.23 %
59        48.27   6.73    Male     No   Sat  Dinner     4        13.94 %
141       34.30   6.70    Male     No  Thur   Lunch     6        19.53 %
..          ...    ...     ...    ...   ...     ...   ...            ...
0         16.99   1.01  Female     No   Sun  Dinner     2         5.94 %
236       12.60   1.00    Male    Yes   Sat  Dinner     2         7.94 %
111        7.25   1.00  Female     No   Sat  Dinner     1        13.79 %
67         3.07   1.00  Female    Yes   Sat  Dinner     1        32.57 %
92         5.75   1.00  Female    Yes   Fri  Dinner     2        17.39 %

[244 rows x 8 columns]

In [114]:
#Додатково виведіть топ-5 найбільших чайових використовуючи метод nlargest.

top_five_tip = df.nlargest(5, 'tip')
top_five_tip

     total_bill    tip   sex smoker   day    time  size tip_percentage
170       50.81  10.00  Male    Yes   Sat  Dinner     3        19.68 %
212       48.33   9.00  Male     No   Sat  Dinner     4        18.62 %
23        39.42   7.58  Male     No   Sat  Dinner     4        19.23 %
59        48.27   6.73  Male     No   Sat  Dinner     4        13.94 %
141       34.30   6.70  Male     No  Thur   Lunch     6        19.53 %